// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB68oxx_orQL5xZ-bre1zuEJNQB3JeDE-I',
    appId: '1:847012056554:web:5e0dd04faf53ebff153693',
    messagingSenderId: '847012056554',
    projectId: 'projectiti-2025',
    authDomain: 'projectiti-2025.firebaseapp.com',
    storageBucket: 'projectiti-2025.firebasestorage.app',
    measurementId: 'G-L48ERMNQBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0Z7KsjotJfsN0gcCkZKpVQncUMM82gkE',
    appId: '1:847012056554:android:b81c585231413d23153693',
    messagingSenderId: '847012056554',
    projectId: 'projectiti-2025',
    storageBucket: 'projectiti-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo6ErY0Q8m5jUhs5Qa-pKqGFIId4sn4Sw',
    appId: '1:847012056554:ios:67bdb97913a50bbd153693',
    messagingSenderId: '847012056554',
    projectId: 'projectiti-2025',
    storageBucket: 'projectiti-2025.firebasestorage.app',
    iosBundleId: 'com.example.flutterTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo6ErY0Q8m5jUhs5Qa-pKqGFIId4sn4Sw',
    appId: '1:847012056554:ios:67bdb97913a50bbd153693',
    messagingSenderId: '847012056554',
    projectId: 'projectiti-2025',
    storageBucket: 'projectiti-2025.firebasestorage.app',
    iosBundleId: 'com.example.flutterTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB68oxx_orQL5xZ-bre1zuEJNQB3JeDE-I',
    appId: '1:847012056554:web:1e02cc90234b83e1153693',
    messagingSenderId: '847012056554',
    projectId: 'projectiti-2025',
    authDomain: 'projectiti-2025.firebaseapp.com',
    storageBucket: 'projectiti-2025.firebasestorage.app',
    measurementId: 'G-XF693C8DES',
  );
}
